### ISSUE TITLE
Require version >= 0.6.2 of scenedetect

### ISSUE THREAD

**Issue by elvis-epx** [Breakthrough/DVR-Scan#150]
**Description of Problem & Solution**

When upgrading DVR-Scan from 1.5.1 to 1.6.0 in Linux (Ubuntu 22.04) we got the following error upon starting dvr-scan:

```
  File "/usr/local/bin/dvr-scan", line 5, in <module>
    from dvr_scan.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/dvr_scan/__main__.py",
line 21, in <module>
    from dvr_scan.cli.controller import parse_settings, run_dvr_scan
  File
"/usr/local/lib/python3.10/dist-packages/dvr_scan/cli/__init__.py", line
26, in <module>
    from dvr_scan.cli.config import ConfigRegistry, CHOICE_MAP,
USER_CONFIG_FILE_PATH
  File
"/usr/local/lib/python3.10/dist-packages/dvr_scan/cli/config.py", line
32, in <module>
    from dvr_scan.scanner import DEFAULT_FFMPEG_INPUT_ARGS,
DEFAULT_FFMPEG_OUTPUT_ARGS
  File "/usr/local/lib/python3.10/dist-packages/dvr_scan/scanner.py",
line 31, in <module>
    from scenedetect.platform import FakeTqdmObject
ImportError: cannot import name 'FakeTqdmObject' from
'scenedetect.platform'
(/usr/local/lib/python3.10/dist-packages/scenedetect/platform.py)
```

The version of scenedetect was

```
Requirement already satisfied: scenedetect in
/usr/local/lib/python3.10/dist-packages (from
dvr-scan[opencv-headless]==1.6) (0.6.0.3)
```

Updating to the latest version of scenerequest resolved the issue:

```
Installing collected packages: scenedetect
  Attempting uninstall: scenedetect
    Found existing installation: scenedetect 0.6.0.3
    Uninstalling scenedetect-0.6.0.3:
      Successfully uninstalled scenedetect-0.6.0.3
Successfully installed scenedetect-0.6.2

```
**Proposed Implementation:**

Add scenerequest >= 0.6.2,  not simply scenerequest, as a requirement
