### ISSUE TITLE
Allow globs as input to enable full-folder scanning

### ISSUE THREAD

**Issue by sveken** [Breakthrough/DVR-Scan#5]
Hello,

Wanting to use this for my dashcam when it is in parking mode, only problem is even in parking mode it only does 3 minute clips over the 8 hours, 

Is there a way to scan a whole folder?

**Comment by Breakthrough** [comment]
Hi @sveken;

Currently there is no way to accomplish this purely via PySceneDetect.  However, you could write a Python or Bash script to accomplish this by running the `scenedetect` command on all files in a given directory.

I'll look into adding this as a possible enhancement for a future release, thanks for your submission.

**Comment by Breakthrough** [comment]
As a possible way of implementation, perhaps allowing globs for the input file would be helpful.

**Comment by Breakthrough** [comment]
From #10, it would also be useful for this to output a list of motion events in a CSV file for each video scanned, to allow automated removal of videos without any motion events.

**Comment by matosconsulting** [comment]
Just wanted to share - for any Windows users who want to scan a folder or subset of folders, here's a quick and dirty command you can use:

`for /F %i in ('dir *.mp4 /b') do dvr-scan -i %i`

This runs a directory listing for all .mp4 commands, and spits out a list of filenames. For each filename, the command "dvr-scan -i [filename]" is run. Amend the command above as necessary to get the results you need (e.g. pass in additional options to dvr-scan, sort the directory listing by date descending, etc...)

**Comment by RikJohnsonUK** [comment]
Same issue here - May 2020:

dvr-scan -i  /home/sysops/Videos/test.avi 
[DVR-Scan] Initializing scan context...
Traceback (most recent call last):
  File "/usr/local/bin/dvr-scan", line 9, in <module>
    load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
  File "build/bdist.linux-x86_64/egg/dvr_scan/__init__.py", line 63, in main
  File "build/bdist.linux-x86_64/egg/dvr_scan/scanner.py", line 78, in __init__
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

**Comment by SKempin** [comment]
Similarly for anyone on MacOS:

```
target="/Users/name/Desktop/"
for f in "$target"*
do
    dvr-scan -i $f -t 0.3 -tb 00:00:05.2000 -tp 00:00:10.2000 -l 20
done
```

**Comment by Breakthrough** [comment]
This is definitely on my radar (see #10), but I won't be able too address some quality of life improvements and the project requires a major refactor before looking into adding new features.  Will get back to this as soon as that's done.

Thank you all for the above batch scripts, they'll likely be very useful for users in the meantime.  Will pin this issue for more visibility.

**Comment by aardvark82** [comment]
Also - on Mac os X - if you have multiple subfolders (the example above only handles video files at 1 level) you can use

- install bash 5 with glob support (Mac OS X standard bash doesn't support
- enable glob
- for f in "$target"/**/*

**Comment by Breakthrough** [comment]
I like your suggestion in #48 to also process files in parallel, @aardvark82 - that should definitely be possible.  I'm working on refactoring the codebase to be more modular/reusable, which definitely supports this goal (and should be a lot cleaner to implement once I'm finished reworking the internal API).

**Comment by jaybeegee66** [comment]
One work around for windows users is to do the following

- open a cmd/dos prompt
- change directory to the one with the files
- output the directory listing to a text file by doing "dir >files.txt"
- using excel parse the file keeping just the filename in column A as an example
- in column B add a formula with the parameters you need eg. ="dvr-scan -i " &  A29 & " -t 0.3 -tb 00:00:05.0000 -tp 00:00:5.0000 -l 60"
- do the same for other rows and copy / paste the value into a batch file

**Comment by Breakthrough** [comment]
Finally managed to get around to fixing this, and will be included in the next release (v1.5).  Summary of upcoming changes:

 - In addition to being specified multiple times, `-i`/`--input` will also now accept multiple paths, allowing for shell wildcard expansion
 - Each path passed to `-i`/`--input` will also have wildcard/glob expansion performed on it directly

This means all of the following forms will work in DVR-Scan v1.5:

    dvr-scan -i folder*.mp4
    dvr-scan -i "folder/*.mp4"
    dvr-scan -i folder_a/* -i "folder_b/*"

**Comment by Breakthrough** [comment]
Beta release including this feature is now out:
https://github.com/Breakthrough/DVR-Scan/releases/tag/v1.5-beta

Feedback is most welcome. :)

**Comment by jaybeegee66** [comment]
> Beta release including this feature is now out: https://github.com/Breakthrough/DVR-Scan/releases/tag/v1.5-beta
> 
> Feedback is most welcome. :)

I am trying the multiple file option using this command but getting an error!

dvr-scan -i e:\video\2013-10-27*.avi -d d:\temp -l 60

First file works fine but does not seem to transition to the next.

[DVR-Scan] Scanning 45 input videos for motion events...
[DVR-Scan] Fatal error: Exception raised in decode thread.
Detected: 2 | Progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21601/21601 [01:34<00:00, 228.95 frames/s]
Traceback (most recent call last):
  File "dvr_scan\__main__.py", line 28, in <module>
  File "dvr_scan\__main__.py", line 24, in main
  File "dvr_scan\cli\controller.py", line 282, in run_dvr_scan
  File "dvr_scan\scanner.py", line 733, in scan_motion
  File "dvr_scan\scanner.py", line 817, in _decode_thread
  File "dvr_scan\video_joiner.py", line 107, in read
AttributeError: 'VideoJoiner' object has no attribute '_get_next_frame'
[3784] Failed to execute script '__main__' due to unhandled exception!

**Comment by Breakthrough** [comment]
@jaybeegee66 sorry there was a bug with that beta, this should work correctly in the latest official release (v1.5.1).  Let me know if the latest version works out for you, thanks!

**Comment by jaybeegee66** [comment]
> @jaybeegee66 sorry there was a bug with that beta, this should work correctly in the latest official release (v1.5.1). Let me know if the latest version works out for you, thanks!

Sounds good thank you - when is the official release due out?

**Comment by Arielblues** [comment]
Hi, am using this command     dvr-scan -i "folder/*.mp4"  for folder scanning. But I noticed the filenames of the motion videos use only the first video name as initial naming. Is it possible that the motion video's use the name of their original video?

**Comment by Breakthrough** [comment]
@Arielblues there's no option for this, but feel free to file a feature request for it.

DVR-Scan treats all input videos as a linear sequence, not individual inputs.  Could you describe a bit more about your use case / why calling DVR-Scan on each file individually wouldn't work for that?

Thanks!
